"""add_equipment_inventory

Revision ID: 0116aaeaf942
Revises: v010_add_job_validation_status
Create Date: 2026-06-25 14:31:21.296736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0116aaeaf942'
down_revision: Union[str, None] = 'v010_add_job_validation_status'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('operator', sa.String(length=20), nullable=True))
    op.add_column('jobs', sa.Column('nro', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('sro', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('pbo', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('pto', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('splitter', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('splitter_port', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('optical_power_dbm', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('cable_length_m', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('ont_serial', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('router_serial', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('mac_address', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('wifi_box_serial', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('validation_status', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('rejected_by_operator', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.create_table('equipment_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('mac_address', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('warehouse', sa.String(length=100), nullable=True),
    sa.Column('vehicle', sa.String(length=100), nullable=True),
    sa.Column('assigned_job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_equipment_inventory_id'), 'equipment_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_inventory_operator'), 'equipment_inventory', ['operator'], unique=False)
    op.create_index(op.f('ix_equipment_inventory_serial_number'), 'equipment_inventory', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_inventory_serial_number'), table_name='equipment_inventory')
    op.drop_index(op.f('ix_equipment_inventory_operator'), table_name='equipment_inventory')
    op.drop_index(op.f('ix_equipment_inventory_id'), table_name='equipment_inventory')
    op.drop_table('equipment_inventory')
    op.drop_column('jobs', 'failure_reason')
    op.drop_column('jobs', 'rejected_by_operator')
    op.drop_column('jobs', 'validation_status')
    op.drop_column('jobs', 'wifi_box_serial')
    op.drop_column('jobs', 'mac_address')
    op.drop_column('jobs', 'router_serial')
    op.drop_column('jobs', 'ont_serial')
    op.drop_column('jobs', 'cable_length_m')
    op.drop_column('jobs', 'optical_power_dbm')
    op.drop_column('jobs', 'splitter_port')
    op.drop_column('jobs', 'splitter')
    op.drop_column('jobs', 'pto')
    op.drop_column('jobs', 'pbo')
    op.drop_column('jobs', 'sro')
    op.drop_column('jobs', 'nro')
    op.drop_column('jobs', 'operator')
    # ### end Alembic commands ###