"""users roles

Revision ID: 9bd7709b492c
Revises: 9c63b447e86f
Create Date: 2026-06-16 15:01:17.260031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd7709b492c'
down_revision: Union[str, None] = '9c63b447e86f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DISPATCHER', 'TECHNICIAN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('jobs', sa.Column('assigned_technician_name', sa.String(length=100), nullable=True))

    equipmenttype = sa.Enum(
        'ONU_INWI',
        'ONT_IAM',
        'ONT_ORANGE',
        'HUAWEI',
        'ZTE',
        'NOKIA',
        name='equipmenttype'
    )
    equipmenttype.create(op.get_bind(), checkfirst=True)

    op.add_column('jobs', sa.Column('equipment_type', sa.Enum('ONU_INWI', 'ONT_IAM', 'ONT_ORANGE', 'HUAWEI', 'ZTE', 'NOKIA', name='equipmenttype'), nullable=True))
    op.add_column('jobs', sa.Column('serial_number', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('gps_latitude', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('gps_longitude', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('before_photo', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('after_photo', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('client_signature', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('real_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('coordinator_comments', sa.Text(), nullable=True))
    jobpriority = sa.Enum(
        'URGENT',
        'HAUTE',
        'NORMALE',
        'FAIBLE',
        name='jobpriority'
    )
    jobpriority.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'jobs',
        sa.Column(
            'priority_new',
            jobpriority,
            nullable=True
        )
    )

    op.execute(
        "UPDATE jobs SET priority_new = 'NORMALE'"
    )

    op.drop_column('jobs', 'priority')

    op.alter_column(
        'jobs',
        'priority_new',
        new_column_name='priority',
        existing_type=jobpriority,
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'priority',
               existing_type=sa.Enum('URGENT', 'HAUTE', 'NORMALE', 'FAIBLE', name='jobpriority'),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('jobs', 'coordinator_comments')
    op.drop_column('jobs', 'real_duration_minutes')
    op.drop_column('jobs', 'client_signature')
    op.drop_column('jobs', 'after_photo')
    op.drop_column('jobs', 'before_photo')
    op.drop_column('jobs', 'gps_longitude')
    op.drop_column('jobs', 'gps_latitude')
    op.drop_column('jobs', 'serial_number')
    op.drop_column('jobs', 'equipment_type')
    op.drop_column('jobs', 'assigned_technician_name')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
